from os import environ 

DARKSKY_API_KEY = environ.get('DARKSKY_API_KEY')
ARC_API_KEY = environ.get('ARC_API_KEY')
TWITTER_API_KEY = environ.get('TWITTER_API_KEY')
TWITTER_API_SECRET = environ.get('TWITTER_API_SECRET')
CLOUDINARY_NAME = environ.get('CLOUDINARY_NAME')
CLOUDINARY_API_KEY = environ.get('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = environ.get('CLOUDINARY_API_SECRET')