source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.6.1"

gem 'rails'
gem 'pg'
gem 'puma'
gem 'bootsnap', require: false
gem 'rails_admin', github: 'sferik/rails_admin'

gem 'sentry-raven'
gem 'geocoder'
gem 'awesome_print'
gem 'bitly'
gem 'activerecord-postgis-adapter'
gem 'rgeo-geojson'
gem 'kramdown'
gem 'slim-rails'
gem 'active_model_serializers'
gem 'aasm'
gem 'fcm'
gem 'active_storage-postgresql'
gem 'down'
gem 'image_processing'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
