source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'aasm'
gem 'awesome_print'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'devise-jwt'
gem 'httparty'
gem 'icalendar'
gem 'icalendar-recurrence'
gem 'jsonapi-resources', '~> 0.10.0'
gem 'pg'
gem 'puma', '~> 4.1'
gem 'rack-cors'
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
gem 'sentry-raven'
gem 'slim-rails'
gem 'timber'
gem 'timber-rack'
gem 'timber-rails', github: 'timberio/timber-ruby-rails', ref: '250326' # rails 6 support
gem 'validates_timeliness', '~> 5.0.0.alpha3'
gem 'webpacker', '~> 4.0'
gem 'open_graph_reader'
gem 'chronic'

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
