source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '~> 6.0.2', '>= 6.0.2.1'
gem 'pg'
gem 'puma', '~> 4.1'
gem 'webpacker', '~> 4.0'
gem 'bootsnap', '>= 1.4.2', require: false
gem 'slim-rails'
gem 'active_model_serializers', '~> 0.10.0'
gem 'validates_timeliness', '~> 5.0.0.alpha3'
gem "sentry-raven"
gem 'aasm'
gem 'awesome_print'
gem 'httparty'
gem 'timber'
gem 'timber-rack'
gem 'timber-rails', github: 'timberio/timber-ruby-rails', ref: '250326b'

group :development do
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
