# Heroku's guidelines: http://bit.ly/2tJWMJR
web: bundle exec puma -C config/puma.rb

# prod-only
release: bundle exec rails db:migrate

# dev-only
webpacker: ./bin/webpack-dev-server
log: tail -f ./log/development.log
# pgweb: pgweb --host=${DATABASE_HOST} --db=${DATABASE_NAME} --ssl=disable
